### ISSUE TITLE
scale factor for CISO tracers

### ISSUE THREAD

**Issue by mnlevy1981** [marbl-ecosys/MARBL#109]
@klindsay28 emailed me the following:

> I suspect that the values of ciso_tracer_init_ext(:)%scale_factor that are not 1.0 are not correct, now that we've changed the ciso IC file.
> 
> For instance, I think the 1.025 value for DI13C, reading from DIC, was replicating the value for DIC from an old ecosys IC file. Now that the ecosys IC file has the 1.025 value applied in the file, and not in the code, it isn't appropriate to apply 1.025 for DI13C. If possible, I think we should change the scale_factor to be the same as the scale factor for DIC. This might be tricky to pull off in build-namelist. If it isn't straightforward, perhaps we should just use 1 for ciso's scale_factor. We might consider removing ciso's scale_factor from namelist defaults and build-namelist.
> 
> Additionally, I think the 0.9225 value for DI14C, reading from DIC, which is intended to account for decay of DI14C, takes into account the old 1.025 factor being applied to DIC. I think we want 0.9 times the factor being used for DIC. For simplicity, we might want to just use 0.9.

The `tracer_init_ext` variables are purely a driver construct now, so this shouldn't require any updates to MARBL

**Comment by klindsay28** [comment]
I spoke with Alex Jahn and she confirmed my suspicion regarding the origin of the non-1.0 scale_factor values for the ciso tracers. So we should change it 1.0 for DI13C.

She also confirmed that the 0.9 value for DI14C is an attempt to represent decay of 14C. However, she suggested that some other value might be better. Some options to consider are
1) 1.0, then deviations in a brute-force spinup are purely due to decay of 14C
2) determine value to get the oldest values correct, compared to obs
3) determine value to minimize duration of a brute-force spinup

Alternatively, we could change decouple the DI14C IC from the BEC IC file and initialize with GLODAP D14C.

Let's talk about this at the next MARBL meeting.

**Comment by klindsay28** [comment]
consensus at 13 Dec MARBL team meeting is to add GLODAP PI DI14C to BEC IC file and add fallback to use DIC with default scalefactor (=1)

**Comment by mnlevy1981** [comment]
So `DI13C` and `DI14C` are both being changed to 1.0? Should the abio scale factors match the ciso scale factors? `ABIO_DIC` uses 1.025 and `ABIO_DIC14` uses 0.9225.

**Comment by klindsay28** [comment]
ABIO_DIC should be 1.0
For now, I think we should set ABIO_DIC14 to 0.9, i.e., 0.9225/1.025.
This is an ad-hoc attempt to account for 14C decay.

**Comment by mnlevy1981** [comment]
Moved to ESCOMP/POP2-CESM#9
