### ISSUE TITLE
Units for input forcing fields?

### ISSUE THREAD

**Issue by mangelesg** [marbl-ecosys/MARBL#367]
Hello,

Im trying to figure which units the input fields should have.

In the MARBL documentation it says Dust Flux should be in g/cm^2/s , however the file containing the inputs (call_compute_subroutines.20190718.nc), shows Dust Flux in kg/m^2/s.

Which are the correct units?

Thanks,

Angeles

**Comment by mnlevy1981** [comment]
Sorry for the confusion -- the netCDF file is in `kg/m^2/s` because we eventually want MARBL's internal computations to be done with units of meters, kilograms, and seconds rather than centimeters, grams, and seconds (see #41). Currently, the stand-alone driver [applies a conversion factor](https://github.com/marbl-ecosys/MARBL/blob/6b2a5e4/tests/driver_src/marbl_io_mod.F90#L459) for many of the forcing fields, and for dust flux the [conversion factor](https://github.com/marbl-ecosys/MARBL/blob/6b2a5e4/tests/driver_src/marbl_io_mod.F90#L1009) is 0.1.

**Comment by mangelesg** [comment]
Thanks for the fast reply!

**Comment by mangelesg** [comment]
Hello,

 Do you know if the units system used in MARBL is the same as used in the Biogeochemical Elemental Cycling model (BEC)?

Thanks!

Angeles

**Comment by mnlevy1981** [comment]
Hi @angeles2013 -- sorry for the delay in responding. MARBL was developed out of BEC in POP2, and in that case we have left the units the same. If you are looking at BEC as ported to a different model, though, it's possible that the units were modified to match the base units in that other model (though I suspect it would be easier to just convert the inputs and outputs)

**Comment by mangelesg** [comment]
@mnlevy1981  thanks for the information!

**Comment by mangelesg** [comment]
The NO3 variable is on units of micromol/Liter, however the NOx flux is on units of nmol/cm2/sec (after using the scale_factor 7.1429e+06).

When the flux NOx is added to NO3, wouldn't be necessary another conversion to match their units? 

Also, NOx is per area, while NO3 is per volume. Is the flux multiplied by the water column height?

**Comment by mnlevy1981** [comment]
The NOx flux is the nitrogen deposition flux and it is added to the surface tracer flux being returned to MARBL (see [line 407 of `marbl_surface_flux_mod.F90`](https://github.com/marbl-ecosys/MARBL/blob/stable/src/marbl_surface_flux_mod.F90#L407)). The units work out, even though it doesn't look like it at first blush:

Note that the NO3 units, `mmol / m^3`, are equivalent to `nmol / cm^3` because `1 mmol` = `1e6 nmol` and also `1 m^3` = `1e6 cm^3` so the 1e6 terms cancel. For the surface fluxes, we multiply the tracer units by velocity (which has units `cm / s`) so `nmol / cm^2 / s` are the proper units for the surface flux of NO3.

**Comment by mangelesg** [comment]
Thank you, but when is the surface tracer flux added to the total tracer?

**Comment by mnlevy1981** [comment]
MARBL doesn't add the surface tracer flux to the total tracer at all, it expects the GCM to know how to do that as part of the vertical mixing routine.

**Comment by mangelesg** [comment]
That helps a lot, thank you
