### ISSUE TITLE
redesign specification of forcing fields

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#56]
have MARBL specify, in a generic sense, which fields it needs,
but specification of forcing field source resides in driver

**Comment by mnlevy1981** [comment]
Note that there are forcing fields for CISO that have not been moved to the `marbl_forcing_fields_type` yet (atmospheric D13C and D14C); as part of resolving this ticket, we need to handle these fields consistently as well.

**Comment by mnlevy1981** [comment]
Re: the comment from June 2 about needing to move D13C and D14C into `marbl_forcing_fields_type` -- those two fields are now in the appropriate place.

@klindsay28 and @matt-long -- can you guys verify that this is an accurate representation of where things stand for forcing fields and also a reasonable description of what we want the code to look like after completing the work in this ticket? I think I might be missing something, maybe other places in the code that use the `marbl_forcing_fields_type` besides the surface forcing? Or maybe a place where we _could_ use a more generalized `marbl_forcing_fields_type` but can't use the current implementation?

---

Currently, surface forcing is handled in MARBL in the following manner:
1. In `config` (either via `marbl_forcing_tmp_nml` or `put()` commands), MARBL determines some settings such as "what file will we read `DIN_RIV_FLUX` from?" and "will we get ice fraction and piston velocity from the driver or will they be read from a file?"
2. In `init`, MARBL sets the internal index for where in the forcing fields datatype the following fields will be stored (indices of 0 imply the field is not requested by MARBL), as well as whether the field will be read from a file or received from the driver
   1. `surface_mask`
   2. `u10_sqr`
   3. `ifrac`
   4. `sst`
   5. `sss`
   6. `atm_pressure`
   7. `xco2`
   8. `xco2_alt`
   9. `xkw`
   10. `dust_flux`
   11. `black_carbon_flux`
   12. `iron_flux`
   13. `nox_flux`
   14. `nhy_flux`
   15. `din_riv_flux`
   16. `dip_riv_flux`
   17. `don_riv_flux`
   18. `dop_riv_flux`
   19. `dsi_riv_flux`
   20. `dfe_riv_flux`
   21. `dic_riv_flux`
   22. `alk_riv_flux`
   23. `doc_riv_flux`
   24. `d13c`
   25. `d14c`
   26. `d14c_glo_avg`
3. During the time stepping loop, the driver populates `marbl%surface_input_forcings` as directed (either by reading the file or just dropping in the correct variable)

---

What we want:
1. In `init`, MARBL specifies what fields it requires [needs to be done after `config` because it will depend on configuration decisions like "are we running with carbon isotopes?"] and returns this to the driver. One possibility is to continue using `marbl%surface_forcing_ind` but I think an array of strings is better because
   1. if a new surface forcing field is added to the list, the driver code may not know to look to see if the index is non-zero
   2. the driver shouldn't need to use `surface_forcing_ind`, and we can take it out of the interface
2. Optional, but maybe in `complete_config_and_init` the driver completes the handshake by letting MARBL know it is capable of providing all the requested fields (if MARBL wants `black_carbon_flux` and the driver doesn't know how to compute it or otherwise obtain it, an abort / error during setup is preferable to unknown behavior in the time loop when the driver just doesn't provide `marbl%surface_input_forcings(:,marbl%surface_forcing_ind%black_carbon_id)`)
3. During the time-stepping loop, the driver populates `marbl%surface_input_forcings` how it sees fit
   1. Just to note, if we do use a string to return the list of all requested surface forcing fields then it should be ordered such that `black_carbon` is the Nth element in the list when `surface_forcing_ind%black_carbon_id = N`. I don't anticipate needing to do string comparisons based on this array inside the time stepping loop.

**Comment by mnlevy1981** [comment]
Available in the marbl0.9.0 tag
