### ISSUE TITLE
investigate and correct units for DUST_FLUX, IRON_FLUX, etc.

### ISSUE THREAD

**Issue by klindsay28** [marbl-ecosys/MARBL#63]
code has comment

```
    ! multiply DUST flux by mpercm (.01) to convert from model units (cm/s)(mmol/m^3) to mmol/s/m^2
```

This is can't be correct, because DUST_FLUX has units g/cm^2/s.

**Comment by mnlevy1981** [comment]
This comment is still in `marbl_diagnostics_mod.F90`

**Comment by mnlevy1981** [comment]
`DUST_FLUX` is definitely coming in from the GCM as `g/cm^2/s`, which are already the units for `DUST_FLUX` and `dustToSed`. We want to change the units for `DUST_FLUX_IN` to be the same, and no need to multiply any dust diagnostics by `mpercm`.

`dust_REMIN` should be `g/cm^3/s` (and also we should output `dust%remin` rather than `P_SiO2%remin`)
